### ISSUE TITLE
Project Todo List

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/sadx-hdgui-prompts#1]
Short Term: COMPLETE!
- [x] Export Switch Pro Controller mod
- [x] Re-export all PS3 stuff with more specific left stick texture and trigger textures
- [x] Use new ZL/ZR prompts from Xelu if he makes them.

??? Term:
- [ ] Maybe improve the textures for the triggers in some cases (sprf_01, sprf_01_e, bprf_42) by making the textures line up on the left. May involve redoing the project files for these, but no big deal.
- [ ] Maaaybe do Switch JoyCon, not sure.

Medium Term:
- [ ] Include Maps (requires those maps to be added to HD GUI 2)

Long Term:
- [ ] Chao Garden UI (when it's added to HD GUI 2 and UI Scaling)
- [ ] Game Gear UI (aka Mini Game Collection, when it's added to HD GUI 2 and UI Scaling)

Oh god I hope not Term:
- [ ] French Language Everything
- [ ] German Language Everything
- [ ] Spanish Language Everything
