### ISSUE TITLE
Release 1.1 Todo List

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/sadx-hdgui-prompts#6]
- [x] Wait for PkR to release the new HDGUI or get it from him early (preferably the latter)
- [x] Test the Plugins (duh!)
- [x] Make Screenshots for Banana
- [x] Update Readme
- [x] Fix anything I screwed up (hopefully nothing!)
- [x] Package 7zs
- [x] Upload Release
- [x] Update Banana

**Comment by cheatfreak47** [comment]
released!
